### ISSUE TITLE
stereo-inertial node can't run well

### ISSUE THREAD

**Issue by wolfgangbiang** [zang09/ORB_SLAM3_ROS2#4]
Hey zang, have you successfully run stereo-inertial mode in realtime?
By my side it also output IMU not initialzation and Empty IMU Measurement Vector!!
Do you have any idea how to solve this?
![77e352da35863cb32eae44c0f9c662e](https://user-images.githubusercontent.com/77690913/220807599-f703ab7a-5b8c-460f-a40f-9a7e49ed6897.jpg)

**Comment by lfescobarc** [comment]
I am having the same issue, I am trying to run using a D435i realsense camera.

**Comment by zang09** [comment]
Hi, i have successfully run in real-time with simulator dataset.
Did you compile with this [repo](https://github.com/zang09/ORB-SLAM3-STEREO-FIXED)? The fixed version of ORB_SLAM3 stereo mode.

**Comment by wolfgangbiang** [comment]
No i do it on original ORB-SLAM3, but by my side , the stereo model works completely fine, The issue happen only when Stereo-Inertial model. Anyway i will try this repo first. Thanks.

**Comment by wolfgangbiang** [comment]
I also use the D455I and even i changed to the orb-slam3-fixed, it still the same condition.  The tracking thread can't work, IMU can't be initialized. I checked ros2 topic of imu. Data streams are there and subscriber topic is correct. Do you have any idea about that?

**Comment by lfescobarc** [comment]
I am working with stereo-inertial as well. I tried both the repo you shared with the fixed ORB-SLAM3 and the official one. I also tested a D455 and a D435i camera, checked the ROS2 rqt_graph, and used the infra1 and infra2 as the left and right cameras. It looks like the imu is also connected to ORB-SLAM3. However, it still not shows any images. I tested the ORB-SLAM3 directly, and it seems to work correctly. Also, I was trying to test the monocular or stereo package with my camera, but whenever I start the "ros2 run orbslam3 <mode>", the program runs and prints Starting the Viewer, but as soon as the orbslam3 windows open, it just closes by itself. Any idea what I am doing wrong? have you tested your code with real-time cameras?. I have not tested the Euroc data, because I have a restriction on not using ROS in the computer I am working on. so I can not install the ros1 and ros2 bridge. I am using Ubuntu 20.04 and Ros2 foxy.

![rqt](https://user-images.githubusercontent.com/90339400/221039778-da864b01-5d19-4673-9aab-809c27cd8522.png)

**Comment by wolfgangbiang** [comment]
> 

Did you check your D435i.yaml file? Calibration parameters may cause your problem.

**Comment by lfescobarc** [comment]
> > 
> 
> Did you check your D435i.yaml file? Calibration parameters may cause your problem.

Yes, I did, what I am not sure is if I need to rectify or not the image when using the Infra1 and 2 as left and right. I am using the yaml file of the 435 as it is in the config folder, and from what I get, ORB SLAM3 should be showing something even with the parameters a little of, can you share your yaml file you used for D455?

**Comment by wolfgangbiang** [comment]
> > > 
> > 
> > 
> > Did you check your D435i.yaml file? Calibration parameters may cause your problem.
> 
> Yes, I did, what I am not sure is if I need to rectify or not the image when using the Infra1 and 2 as left and right. I am using the yaml file of the 435 as it is in the config folder, and from what I get, ORB SLAM3 should be showing something even with the parameters a little of, can you share your yaml file you used for D455?

Sorry for later respone, i just uesed the default yaml of D435i, i remeber i had the same issue like you before. No images input, so i changed one router, after that, i can recive the images. It may happen when the bandwidth is not enough. But i'm not sure whether this method also suitable for you.

**Comment by lfescobarc** [comment]
I can try. Do you mean an actual router or something on the code? sorry for the basic question, but I do not understand what you mean with router there.

**Comment by wolfgangbiang** [comment]
> I can try. Do you mean an actual router or something on the code? sorry for the basic question, but I do not understand what you mean with router there.

WLAN router

**Comment by LIBOZH97** [comment]
I met the same problem,i tried to combine ros2 orbslam3 with gazebo,when i run the code,there was no output on the orbslam3,but the ralation of topic is correct,i really don't know what going on.
